name: Build

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      SHA256_arm64_macos:
        description: 'SHA256 checksum for arm64-macos binary'
        value: ${{ jobs.build.outputs.SHA256_arm64_macos }}
      SHA256_x86_64_macos:
        description: 'SHA256 checksum for x86_64-macos binary'
        value: ${{ jobs.build.outputs.SHA256_x86_64_macos }}
      SHA256_x86_64_linux:
        description: 'SHA256 checksum for x86_64-linux binary'
        value: ${{ jobs.build.outputs.SHA256_x86_64_linux }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15
            target: aarch64-apple-darwin
            sha: SHA256_arm64_macos
          - os: macos-13
            target: x86_64-apple-darwin
            sha: SHA256_x86_64_macos
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            sha: SHA256_x86_64_linux
    outputs:
      SHA256_arm64_macos: ${{ steps.checksum.outputs.SHA256_arm64_macos }}
      SHA256_x86_64_macos: ${{ steps.checksum.outputs.SHA256_x86_64_macos }}
      SHA256_x86_64_linux: ${{ steps.checksum.outputs.SHA256_x86_64_linux }}
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ matrix.target }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.target }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target/
          key: ${{ matrix.target }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.target }}-cargo-build-

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y librime-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install librime

      - name: Build
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            # Set librime paths for Homebrew installation
            if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
              export LIBRIME_INCLUDE_DIR=/opt/homebrew/include
              export LIBRIME_LIB_DIR=/opt/homebrew/lib
            else
              export LIBRIME_INCLUDE_DIR=/usr/local/include
              export LIBRIME_LIB_DIR=/usr/local/lib
            fi
          fi
          cargo build --release

      - name: Archive
        run: |
          tar czvf rime_ls-${{ matrix.target }}.tar.gz -C target/release/ rime_ls

      - name: Compute SHA256
        id: checksum
        run: |
          SHA256=$(shasum -a 256 rime_ls-${{ matrix.target }}.tar.gz | awk '{print $1 }')
          echo "${{ matrix.sha }}=$SHA256" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rime_ls-${{ matrix.target }}.tar.gz
          path: rime_ls-${{ matrix.target }}.tar.gz
