name: Update Homebrew Tap

on:
  workflow_call:
    inputs:
      release_tag:
        description: "The tag of the release to update the formula for."
        type: string
        required: true
      dry_run:
        description: "Whether to skip creating the pull request."
        type: boolean
        required: true

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for release and download assets
        id: download_assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          start_time=$(date +%s)
          timeout=300
          interval=20

          echo "Waiting for release assets for tag: ${{ inputs.release_tag }}"

          while true; do
            sleep $interval

            current_time=$(date +%s)
            if [ $((current_time - start_time)) -gt $timeout ]; then
              echo "Error: Timed out after ${timeout} seconds waiting for release assets."
              exit 1
            fi

            # Try to download assets using gh release download
            if gh release download ${{ inputs.release_tag }} --repo ${{ github.repository }} --pattern '*x86_64-apple-darwin*' --pattern '*aarch64-apple-darwin*' --pattern '*x86_64-unknown-linux-gnu*'; then
              echo "All release assets downloaded successfully"
              break
            fi

            echo "Waiting ${interval}s..."
          done

      - name: Calculate SHA256 checksums
        id: checksums
        run: |
          set -euo pipefail
          # Calculate SHA256 hashes
          SHA_X86_64_MACOS=$(shasum -a 256 rime_ls-x86_64-apple-darwin.tar.gz | cut -d' ' -f1)
          SHA_ARM64_MACOS=$(shasum -a 256 rime_ls-aarch64-apple-darwin.tar.gz | cut -d' ' -f1)
          SHA_X86_64_LINUX=$(shasum -a 256 rime_ls-x86_64-unknown-linux-gnu.tar.gz | cut -d' ' -f1)

          echo "SHA_X86_64_MACOS=$SHA_X86_64_MACOS" >> $GITHUB_ENV
          echo "SHA_ARM64_MACOS=$SHA_ARM64_MACOS" >> $GITHUB_ENV
          echo "SHA_X86_64_LINUX=$SHA_X86_64_LINUX" >> $GITHUB_ENV

      - name: Check out tap repository
        uses: actions/checkout@v4
        with:
          repository: twio142/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update formula from template
        run: |
          VERSION=${{ inputs.release_tag }}
          sed -e "s/%%VERSION%%/${VERSION#v}/g" \
              -e "s/%%SHA_X86_64_MACOS%%/${{ env.SHA_X86_64_MACOS }}/g" \
              -e "s/%%SHA_ARM64_MACOS%%/${{ env.SHA_ARM64_MACOS }}/g" \
              -e "s/%%SHA_X86_64_LINUX%%/${{ env.SHA_X86_64_LINUX }}/g" \
              Formula/rime-ls.rb.template > Formula/rime-ls.rb

          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            cat Formula/rime-ls.rb
          fi

      - name: Create pull request
        if: ${{ !inputs.dry_run }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "chore: bump rime-ls to ${{ inputs.release_tag }}"
          title: "Bump rime-ls to ${{ inputs.release_tag }}"
          body: "Automated release for rime-ls version ${{ inputs.release_tag }}"
          branch: "bump-rime-ls-${{ inputs.release_tag }}"
          base: main
          delete-branch: true
          add-paths: "Formula/rime-ls.rb"
