name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-mod"

permissions:
  contents: read

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release_info.outputs.tag }}
    steps:
      - name: Set Release Tag
        id: release_info
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.ref_type }}" == "tag" ]]; then
              echo "tag=${{ github.ref_name }}-${{ github.run_id }}" >> $GITHUB_OUTPUT
            else
              echo "tag=v0.0.0-${{ github.run_id }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [release-info, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-info.outputs.tag }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          files: |
            rime_ls-x86_64-unknown-linux-gnu.tar.gz
            rime_ls-x86_64-apple-darwin.tar.gz
            rime_ls-aarch64-apple-darwin.tar.gz

  update-homebrew-tap:
    needs: [release-info, release]
    uses: ./.github/workflows/homebrew.yml
    with:
      release_tag: ${{ needs.release-info.outputs.tag }}
      dry_run: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
